**1.How do you create a 1D array of numbers from 0 to 9 using NumPy?**

In [1]:
import numpy as np
array = np.arange(10)
array


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

**2. How can you create a 2D array with 3 rows and 4 columns filled with zeros?**

In [2]:
ma= np.zeros((3, 4))
ma

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

**3. What is the difference between arange() and linspace() in NumPy?**

**#arange**

In [3]:
array = np.arange(10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

**#linspace**

In [4]:
array = np.linspace(0, 20,3)
array

array([ 0., 10., 20.])

**#4.How can you create a NumPy array with random values?**

In [5]:
# Creating a 2x3 array of random floats between 0 and 1
array = np.random.rand(2, 3)
array

array([[0.17267598, 0.58518676, 0.46129431],
       [0.63630784, 0.48451942, 0.42453832]])

**# 5. How do you perform element-wise addition of two arrays in NumPy?**

In [6]:
array1= np.array([2,3,4])
array2= np.array([5,6,7])
result= np.add(array1 ,array2)
print(result)

[ 7  9 11]


**# 6. How can you find the maximum value in a NumPy array?**


In [7]:
array= [1,3,44,55,64,23,6,7,8,99,21,456]
max_value= np.max(array)
max_value

456

**# 7. How can you flatten a 2D NumPy array into a 1D array?**

In [8]:
array=np.array([[1,2,3],
                [4,5,6]])
array1=array.flatten()
array1

array([1, 2, 3, 4, 5, 6])

**# 8. How do you change the shape of a NumPy array from 3x3 to 1x9?**

In [9]:
array=np.array([[1,2,3],[2,3,6],
                [2,4,7]])
reshape_array= array.reshape(1,9)
reshape_array

array([[1, 2, 3, 2, 3, 6, 2, 4, 7]])

**# 9. How can you transpose a matrix in NumPy?**

In [10]:
import numpy as np

# Creating a 2x3 matrix
mat = np.array([[1, 2, 3], 
                   [4, 5, 6],
               [7,8,9]])

# Transposing the matrix
transposed_matrix = np.transpose(mat)
transposed_matrix

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

**# 10.How do you find the sum of all elements in a NumPy array?**

In [11]:
# Creating a 1D array
array = np.array([1, 2, 3, 4, 5])

# Finding the sum of all elements
total_sum = np.sum(array)
total_sum


15

**11.How can you get the mean, median, and standard deviation of a NumPy
array?**

In [12]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])


In [13]:
mean = np.mean(arr)
mean

5.0

In [14]:
median = np.median(arr)
median

5.0

In [15]:
std_dev = np.std(arr)
std_dev

2.581988897471611

**12.How can you slice a 3x3 NumPy array to get the first two rows?**

In [16]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

first_two_rows = arr[:2, :]
first_two_rows


array([[1, 2, 3],
       [4, 5, 6]])

**13.How can you find the index of the maximum value in a NumPy array?**

In [17]:
arr = np.array([1, 3, 7, 9, 2, 51])
max_index = np.argmax(arr)
max_index

5

**14.How do you select all elements greater than 5 in a NumPy array?**

In [18]:
arr = np.array([1, 6, 3, 8, 5, 7])
greater_than_5 = arr[arr > 5]
greater_than_5

array([6, 8, 7])

**15.How can you perform matrix multiplication with NumPy?**

In [19]:
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])
result = np.matmul(A, B)
result

array([[19, 22],
       [43, 50]])

**16.How do you create a 4x4 identity matrix using NumPy?**

In [20]:
identity_matrix = np.eye(4)
identity_matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

**17.How can you replace all elements in a NumPy array that are less than 0
with 0?**

In [21]:
arr = np.array([-3, 2, -1, 4, -5])
arr[arr < 0] = 0
arr

array([0, 2, 0, 4, 0])

**18.How do you stack two arrays vertically in NumPy?**

In [22]:
array1 = np.array([[1, 2, 3],
                   [4, 5, 6]])

array2 = np.array([[7, 8, 9],
                   [10, 11, 12]])

stacked_array = np.vstack((array1, array2))
stacked_array

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

**19.How do you stack two arrays horizontally in NumPy?**

In [23]:
array1 = np.array([[1, 2, 3],
                   [4, 5, 6]])

array2 = np.array([[7, 8, 9],
                   [10, 11, 12]])

stacked_array = np.hstack((array1, array2))
stacked_array

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

**20.How can you create a NumPy array from a Python list?**

In [24]:
python_list = [1, 2, 3, 4, 5]
numpy_array = np.array(python_list)
numpy_array

array([1, 2, 3, 4, 5])

**21.How can you concatenate two arrays along a specified axis in NumPy?**

In [25]:
array1 = np.array([[1, 2, 3],
                   [4, 5, 6]])

array2 = np.array([[7, 8, 9],
                   [10, 11, 12]])

result_axis0 = np.concatenate((array1, array2), axis=0)

result_axis1 = np.concatenate((array1, array2), axis=1)


print("Concatenated along axis 0:")
print(result_axis0)

print("\nConcatenated along axis 1:")
print(result_axis1)


Concatenated along axis 0:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Concatenated along axis 1:
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


**22.How do you perform element-wise division of two arrays in NumPy?**

In [26]:
array1 = np.array([10, 20, 30])
array2 = np.array([2, 4, 5])
result = array1 / array2
result

array([5., 5., 6.])

**23.How do you find the unique elements in a NumPy array?**

In [27]:
array = np.array([1, 2, 2, 3, 4, 4, 5])
UNIQE= np.unique(array)
UNIQE

array([1, 2, 3, 4, 5])

**24.How can you get the dot product of two vectors using NumPy?**

In [28]:
vector1 = np.array([1, 2, 3])
vector2 = np.array([4, 5, 6])
dot_product = np.dot(vector1, vector2)
dot_product

32

**25.How do you sort a NumPy array in ascending order?**

In [29]:
array = np.array([5, 2, 9, 1, 5, 6])
sorted_array = np.sort(array)
sorted_array

array([1, 2, 5, 5, 6, 9])